### PR TITLE
Open lbtcl registration

### PR DESCRIPTION
**Pull request by keraliss**
Screenshot from 2024-08-20 14-18-57
Screenshot from 2024-08-20 14-19-10

### CODE REVIEW

**Comment by keraliss** [comment]
Screenshot from 2024-08-22 10-52-07
Screenshot from 2024-08-22 10-53-39
Screenshot from 2024-08-22 10-55-10
Screenshot from 2024-08-22 10-55-13
Screenshot from 2024-08-22 10-55-16
Screenshot from 2024-08-22 10-55-19
Screenshot from 2024-08-22 10-55-22
Screenshot from 2024-08-22 10-55-24
Screenshot from 2024-08-22 10-55-31
Screenshot from 2024-08-22 10-55-35
Screenshot from 2024-08-22 10-55-57
Screenshot from 2024-08-22 10-56-01
Screenshot from 2024-08-22 10-56-04
Screenshot from 2024-08-22 10-56-09
Screenshot from 2024-08-22 10-56-13
Screenshot from 2024-08-22 10-56-16
Screenshot from 2024-08-22 10-56-20
Screenshot from 2024-08-22 10-56-23
Screenshot from 2024-08-22 10-56-29

**Comment by keraliss** [comment]
Screenshot from 2024-08-22 18-23-10
Screenshot from 2024-08-22 18-23-16

**Comment by setusaurabh** [comment]
The updated design looks good to me.

We should comment out the reg_deadline, so that the code remains when we wish to add it there.

**Review by rajarshimaitra — APPROVED** [review]
Ack

**Pull request merged**
