### PR TITLE
fixes #176 : added new posters, badges and dates for the cohort

### LINKED ISSUE #176: Keeping all the cohorts listed, taking in application and showing the current status
@rajarshimaitra and I can finalize the dates for the cohorts. And we will begin the cohorts then.

Mastering Bitcoin -  4 April
LBTCL - Sep 20
BPD - Nov 15
PB - 10 Jan

@paperpsych remove the dates from the banner like LBTCL. @keraliss pls figure out if there's a way to add tags or the last date for the cohort on the banner itself and let participants know this is the one starting next or currently live.

### PR DESCRIPTION
**Pull request by keraliss**
Screenshot from 2024-08-07 14-43-11
Screenshot from 2024-08-07 14-49-47
Screenshot from 2024-08-07 14-50-50
Screenshot from 2024-08-07 14-50-55
Screenshot from 2024-08-07 14-51-02
Screenshot from 2024-08-07 14-51-06

### CODE REVIEW

**Comment by setusaurabh** [comment]
Good job with Tags @keraliss.

I'd vote for the tags to be 

- "Ongoing" 
- "Applications Open" 
- "Coming Soon"  

Also for the copy lets simplify and call it: Cohort Starts on XYZ

**Comment by keraliss** [comment]
Screenshot from 2024-08-07 18-32-51
Screenshot from 2024-08-07 18-33-03

**Comment by keraliss** [comment]
Screenshot from 2024-08-07 19-42-08

**Review by rajarshimaitra — APPROVED** [review]
ACK

**Pull request merged**
