### PR TITLE
[Talks] Header #29 , [Review] Header #24 , [LBTCL] Header #32

### LINKED ISSUE #24: [Review] Header
Screenshot 2023-11-19 at 12 01 27 PM

### LINKED ISSUE #29: [Talks] Header
Screenshot 2023-11-19 at 12 17 38 PM

### LINKED ISSUE #32: [LBTCL] Header
Screenshot 2023-11-19 at 12 22 23 PM

### PR DESCRIPTION
**Pull request by keraliss**
fixes #24
fixes #29 
fixes #32 
This contains 
[LBTCL] Header #32
[Review] Header #24
[Talks] Header #29
also header for deep dive

Screenshot from 2023-11-20 17-02-34
Screenshot from 2023-11-20 17-03-06
Screenshot from 2023-11-20 17-03-16
Screenshot from 2023-11-20 17-03-31
Screenshot from 2023-11-20 17-03-52
Screenshot from 2023-11-20 17-03-57
Screenshot from 2023-11-20 17-04-05
Screenshot from 2023-11-20 17-04-12

### CODE REVIEW

**Review by emjshrx — COMMENTED** [review]
Awesome work 👏👏. No comments on new code. Can you replace existing headers as well?

**Review by emjshrx — COMMENTED** [review]
Also pls remove the deep dive page as its not there for v1

**Comment by rajarshimaitra** [comment]
If deep dive is already done, it can stay.. Doesn't hurt.. We only have few videos and may add more later.. But whatever is there can remain.

**Comment by emjshrx** [comment]
> If deep dive is already done, it can stay.. Doesn't hurt.. We only have few videos and may add more later.. But whatever is there can remain.

Just the header for deep dive is done. We can have the videos for now in the Bitcoin Talks page? @rajarshimaitra

**Comment by emjshrx** [comment]
fixes #24 #29 #32

**Review by emjshrx — APPROVED** [review]

**Comment by rajarshimaitra** [comment]
> . We can have the videos for now in the Bitcoin Talks page? 

Yes. We might not expose this page now. Those videos are still WIP.

**Pull request merged**
